apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: techitfactory-prod

resources:
  - ../../../base/frontend

images:
  - name: IMAGE_PLACEHOLDER
    newName: <AWS_ACCOUNT>.dkr.ecr.ap-south-1.amazonaws.com/techitfactory/frontend
    newTag: v1.0.0

replicas:
  - name: frontend
    count: 3
